<?php
$spConfig = array(
	"db"=>array(
		'host'=>'localhost',
		'login'=>'root',
		'password'=>'1111',
		'database'=>'backpackers',	
	),
	'view'=>array(
		'enabled'=>TRUE,
		'config'=>array(
			'template_dir'=>APP_PATH.'/tpl',
			'compile_dir'=>APP_PATH.'/tmp',
			'cache_dir'=>APP_PATH.'/tmp',
			'left_delimiter'=>'<{',
			'right_delimiter'=>'}>',		
		),	
	),
);